### ISSUE TITLE
About Tags & Links

### ISSUE THREAD

**Issue by nanjingman** [ElsaTam/obsidian-extended-graph#2]
I have made the following settings, but the graph not displaying properly. How can I solve this problem. Thank you!
![image](https://github.com/user-attachments/assets/53dee2d0-3c31-41bf-89ae-7336ed858558)

![image](https://github.com/user-attachments/assets/3466b7c7-31b7-476e-a2c4-8a6ad7c31e76)

**Comment by ElsaTam** [comment]
Hi! Did you try to close and reopen the graph?

**Comment by nanjingman** [comment]
Yes，I did.

**Comment by ElsaTam** [comment]
Ok. Give me a few minutes, I will try to create the same set up on my side and see what's wrong :)

**Comment by nanjingman** [comment]
Thanks!

**Comment by nanjingman** [comment]
I create a new vault, and just install this plugin, it works well!

**Comment by ElsaTam** [comment]
I found the reasons for the two issues:
- Links types for notes in folders won't work
- Tags in the frontmatter are not found (I think)

I will fix that and let you know when it's ready. Thanks a lot for reporting, I hadn't think about folders yet ^^'

**Comment by nanjingman** [comment]
You are so nice!

**Comment by ElsaTam** [comment]
@nanjingman It should all be fixed, you can update via BRAT :)

**Comment by nanjingman** [comment]
Good！ Good！ Good！
